-- MySQL Script generated by MySQL Workbench
-- Wed Oct 25 19:47:26 2023
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
-- -----------------------------------------------------
-- Schema basereserva
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema basereserva
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `basereserva` DEFAULT CHARACTER SET utf8 ;
USE `basereserva` ;

-- -----------------------------------------------------
-- Table `basereserva`.`empleados`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `basereserva`.`empleados` ;

CREATE TABLE IF NOT EXISTS `basereserva`.`empleados` (
  `idempleado` INT(11) NOT NULL AUTO_INCREMENT,
  `usuario` VARCHAR(15) NOT NULL,
  `clave` VARCHAR(20) NULL DEFAULT NULL,
  `estado` BIT(1) NULL DEFAULT NULL,
  `alias` VARCHAR(20) NULL DEFAULT NULL,
  PRIMARY KEY (`idempleado`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `basereserva`.`habitaciones`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `basereserva`.`habitaciones` ;

CREATE TABLE IF NOT EXISTS `basereserva`.`habitaciones` (
  `idhabitacion` INT(11) NOT NULL AUTO_INCREMENT,
  `numero` VARCHAR(4) NOT NULL,
  `descripcion` VARCHAR(255) NULL DEFAULT NULL,
  `caracteristicas` VARCHAR(512) NULL DEFAULT NULL,
  `precio_diario` DECIMAL(7,2) NOT NULL,
  `estado` BIT(1) NOT NULL,
  `tipo_habitacion` VARCHAR(20) NULL DEFAULT NULL,
  PRIMARY KEY (`idhabitacion`))
ENGINE = InnoDB
AUTO_INCREMENT = 2
DEFAULT CHARACTER SET = armscii8;


-- -----------------------------------------------------
-- Table `basereserva`.`huespedes`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `basereserva`.`huespedes` ;

CREATE TABLE IF NOT EXISTS `basereserva`.`huespedes` (
  `idhuesped` INT(11) NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(20) NOT NULL,
  `apellido` VARCHAR(20) NOT NULL,
  `tipo_documento` VARCHAR(15) NOT NULL,
  `nro_documento` VARCHAR(8) NOT NULL,
  `direccion` VARCHAR(50) NOT NULL,
  `telefono` VARCHAR(8) NULL DEFAULT NULL,
  `email` VARCHAR(25) NULL DEFAULT NULL,
  PRIMARY KEY (`idhuesped`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `basereserva`.`reservas`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `basereserva`.`reservas` ;

CREATE TABLE IF NOT EXISTS `basereserva`.`reservas` (
  `idreserva` INT(11) NOT NULL AUTO_INCREMENT,
  `idhabitacion` INT(11) NULL DEFAULT NULL,
  `idhuesped` INT(11) NULL DEFAULT NULL,
  `idempleado` INT(11) NULL DEFAULT NULL,
  `tipo_reserva` VARCHAR(20) NULL DEFAULT NULL,
  `fecha_ingreso` DATE NULL DEFAULT NULL,
  `fecha_salida` DATE NULL DEFAULT NULL,
  `costo_alojamiento` DECIMAL(7,2) NULL DEFAULT NULL,
  `estado` BIT(1) NULL DEFAULT NULL,
  PRIMARY KEY (`idreserva`),
  INDEX `fk_reservas_idhabitacion` (`idhabitacion` ASC),
  INDEX `fk_reservas_idhuesped` (`idhuesped` ASC),
  INDEX `fk_reservas_idempleado` (`idempleado` ASC),
  CONSTRAINT `fk_reservas_idempleado`
    FOREIGN KEY (`idempleado`)
    REFERENCES `basereserva`.`empleados` (`idempleado`),
  CONSTRAINT `fk_reservas_idhabitacion`
    FOREIGN KEY (`idhabitacion`)
    REFERENCES `basereserva`.`habitaciones` (`idhabitacion`),
  CONSTRAINT `fk_reservas_idhuesped`
    FOREIGN KEY (`idhuesped`)
    REFERENCES `basereserva`.`huespedes` (`idhuesped`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
